# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HashGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_HashGenerator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BackgroundBehind_2 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_2.setEnabled(True)
        self.BackgroundBehind_2.setGeometry(QtCore.QRect(15, 15, 661, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundBehind_2.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_2.setFont(font)
        self.BackgroundBehind_2.setToolTipDuration(0)
        self.BackgroundBehind_2.setAutoFillBackground(False)
        self.BackgroundBehind_2.setStyleSheet("background: rgba(10,10, 10,150);\n"
"border: 1px solid rgba(255,255, 255,160);\n"
"\n"
"border-radius:5px;\n"
"")
        self.BackgroundBehind_2.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_2.setText("")
        self.BackgroundBehind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_2.setObjectName("BackgroundBehind_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(560, 15, 111, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.help_btn.setMinimumSize(QtCore.QSize(18, 18))
        self.help_btn.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.help_btn.setFont(font)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("background-color: rgb(5,195,221);\n"
"color: rgb(0, 0, 0);\n"
"border-radius:8px;")
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMinimize.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius:8px;")
        self.pushButtonMinimize.setText("")
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.horizontalLayout.addWidget(self.pushButtonMinimize)
        self.pushButtonMaximiz = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMaximiz.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMaximiz.setStyleSheet("background-color: rgb(255, 226, 0);\n"
"border-radius:8px;")
        self.pushButtonMaximiz.setText("")
        self.pushButtonMaximiz.setObjectName("pushButtonMaximiz")
        self.horizontalLayout.addWidget(self.pushButtonMaximiz)
        self.pushButtonExit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("background-color:rgb(255, 97, 6);\n"
"border-radius:8px;")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.back = QtWidgets.QLabel(self.centralwidget)
        self.back.setEnabled(True)
        self.back.setGeometry(QtCore.QRect(0, 0, 691, 391))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("")
        self.back.setText("")
        self.back.setPixmap(QtGui.QPixmap("PVS/BackG.jpg"))
        self.back.setScaledContents(True)
        self.back.setObjectName("back")
        self.yourtext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.yourtext.setGeometry(QtCore.QRect(15, 84, 451, 91))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.yourtext.setFont(font)
        self.yourtext.setStyleSheet("background: rgba(10,10, 10,150);\n"
"color: #eeeeee;\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"padding-top: 7;\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border-radius:5px;\n"
"")
        self.yourtext.setPlainText("")
        self.yourtext.setPlaceholderText("")
        self.yourtext.setObjectName("yourtext")
        self.pasttext = QtWidgets.QPushButton(self.centralwidget)
        self.pasttext.setEnabled(True)
        self.pasttext.setGeometry(QtCore.QRect(480, 84, 196, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasttext.sizePolicy().hasHeightForWidth())
        self.pasttext.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pasttext.setFont(font)
        self.pasttext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasttext.setStyleSheet("background: rgba(10,10, 10,150);\n"
"color: #ffd31a;\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border-radius:4px;\n"
"")
        self.pasttext.setObjectName("pasttext")
        self.selectfile = QtWidgets.QPushButton(self.centralwidget)
        self.selectfile.setGeometry(QtCore.QRect(480, 135, 196, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectfile.sizePolicy().hasHeightForWidth())
        self.selectfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selectfile.setFont(font)
        self.selectfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectfile.setStyleSheet("background: rgba(10,10, 10,150);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border-radius:4px;\n"
"")
        self.selectfile.setObjectName("selectfile")
        self.yourhash = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.yourhash.setEnabled(True)
        self.yourhash.setGeometry(QtCore.QRect(15, 209, 451, 91))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.yourhash.setFont(font)
        self.yourhash.setStyleSheet("background: rgba(10,10, 10,150);\n"
"color: #eeeeee;\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #5488ff,stop:1 #a5fecb);\n"
"padding-top: 7;\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border-radius:5px;\n"
"")
        self.yourhash.setPlaceholderText("")
        self.yourhash.setObjectName("yourhash")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(480, 209, 194, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background: rgba(10,10, 10,100);\n"
"color : #82cbe1;\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #5488ff,stop:1 #a5fecb);\n"
"padding-left: 10;\n"
"border-radius:4;\n"
"\n"
"\n"
"\n"
"")
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.copyhash = QtWidgets.QPushButton(self.centralwidget)
        self.copyhash.setGeometry(QtCore.QRect(480, 260, 196, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyhash.sizePolicy().hasHeightForWidth())
        self.copyhash.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.copyhash.setFont(font)
        self.copyhash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copyhash.setStyleSheet("background: rgba(10,10, 10,150);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #5488ff,stop:1 #a5fecb);\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #5488ff,stop:1 #a5fecb);\n"
"\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border-radius:4px;\n"
"")
        self.copyhash.setObjectName("copyhash")
        self.generatehash = QtWidgets.QPushButton(self.centralwidget)
        self.generatehash.setGeometry(QtCore.QRect(480, 330, 196, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatehash.sizePolicy().hasHeightForWidth())
        self.generatehash.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generatehash.setFont(font)
        self.generatehash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generatehash.setStyleSheet("background: rgba(10,10, 10,150);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#FDFC47, stop:1 #24FE41);\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#FDFC47, stop:1 #24FE41);\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border-radius:4px;\n"
"")
        self.generatehash.setObjectName("generatehash")
        self.lbltext = QtWidgets.QLabel(self.centralwidget)
        self.lbltext.setGeometry(QtCore.QRect(15, 60, 451, 27))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbltext.setFont(font)
        self.lbltext.setStyleSheet("color: rgb(200, 200, 200,255);\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);")
        self.lbltext.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltext.setObjectName("lbltext")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(15, 330, 451, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background: rgba(10,10, 10,150);\n"
"border-radius :5px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#FDFC47, stop:1 #24FE41);\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#FDFC47, stop:1 #24FE41);\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"\n"
"border-radius :5px;\n"
"}      ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.BackgroundBehind_3 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_3.setEnabled(True)
        self.BackgroundBehind_3.setGeometry(QtCore.QRect(15, 60, 451, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundBehind_3.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_3.setFont(font)
        self.BackgroundBehind_3.setToolTipDuration(0)
        self.BackgroundBehind_3.setAutoFillBackground(False)
        self.BackgroundBehind_3.setStyleSheet("background: rgba(10,10, 10,255);\n"
"\n"
"")
        self.BackgroundBehind_3.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_3.setText("")
        self.BackgroundBehind_3.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_3.setObjectName("BackgroundBehind_3")
        self.BackgroundBehind_4 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_4.setEnabled(True)
        self.BackgroundBehind_4.setGeometry(QtCore.QRect(15, 185, 451, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundBehind_4.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_4.setFont(font)
        self.BackgroundBehind_4.setToolTipDuration(0)
        self.BackgroundBehind_4.setAutoFillBackground(False)
        self.BackgroundBehind_4.setStyleSheet("background: rgba(10,10, 10,255);\n"
"\n"
"")
        self.BackgroundBehind_4.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_4.setText("")
        self.BackgroundBehind_4.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_4.setObjectName("BackgroundBehind_4")
        self.lblhash = QtWidgets.QLabel(self.centralwidget)
        self.lblhash.setGeometry(QtCore.QRect(15, 185, 451, 27))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblhash.setFont(font)
        self.lblhash.setStyleSheet("color: rgb(200, 200, 200,255);\n"
"border: 1px solid white;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #5488ff,stop:1 #a5fecb);")
        self.lblhash.setAlignment(QtCore.Qt.AlignCenter)
        self.lblhash.setObjectName("lblhash")
        self.complete = QtWidgets.QPushButton(self.centralwidget)
        self.complete.setGeometry(QtCore.QRect(45, 334, 421, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.complete.sizePolicy().hasHeightForWidth())
        self.complete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.complete.setFont(font)
        self.complete.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.complete.setStyleSheet("background: rgba(0,0, 0,0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#FDFC47, stop:1 #24FE41);\n"
"\n"
"")
        self.complete.setText("")
        self.complete.setObjectName("complete")
        self.back.raise_()
        self.BackgroundBehind_2.raise_()
        self.yourhash.raise_()
        self.layoutWidget.raise_()
        self.yourtext.raise_()
        self.pasttext.raise_()
        self.selectfile.raise_()
        self.comboBox.raise_()
        self.copyhash.raise_()
        self.generatehash.raise_()
        self.progressBar.raise_()
        self.BackgroundBehind_3.raise_()
        self.lbltext.raise_()
        self.BackgroundBehind_4.raise_()
        self.lblhash.raise_()
        self.complete.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        self.pushButtonExit.clicked.connect(MainWindow.close) # type: ignore
        self.pushButtonMinimize.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hash Generator"))
        self.help_btn.setText(_translate("MainWindow", "H"))
        self.pasttext.setText(_translate("MainWindow", "Paste Text"))
        self.selectfile.setText(_translate("MainWindow", "Select File"))
        self.comboBox.setToolTip(_translate("MainWindow", "Select Hash Algorithms"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Hash Algorithm"))
        self.comboBox.setItemText(1, _translate("MainWindow", "md4"))
        self.comboBox.setItemText(2, _translate("MainWindow", "md5"))
        self.comboBox.setItemText(3, _translate("MainWindow", "sm3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "mdc2"))
        self.comboBox.setItemText(5, _translate("MainWindow", "sha1"))
        self.comboBox.setItemText(6, _translate("MainWindow", "blake2b"))
        self.comboBox.setItemText(7, _translate("MainWindow", "blake2s"))
        self.comboBox.setItemText(8, _translate("MainWindow", "whirlpool"))
        self.comboBox.setItemText(9, _translate("MainWindow", "ripemd160"))
        self.comboBox.setItemText(10, _translate("MainWindow", "shake128"))
        self.copyhash.setText(_translate("MainWindow", "Copy Hash"))
        self.generatehash.setText(_translate("MainWindow", "Generate Hash"))
        self.lbltext.setText(_translate("MainWindow", "Your Text"))
        self.lblhash.setText(_translate("MainWindow", "Your Hash"))